name: CI Develop

on:
  push:
    branches:
      - 'develop'

  pull_request:
    branches:
      - 'develop'

env:
  BASE: ${{ github.ref == 'refs/heads/develop' && 'origin/develop~1' || 'origin/develop' }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn install

      - name: Lint mono
        run: npx nx affected:lint --base $BASE

      - name: Build mono
        run: npx nx affected:build --base $BASE
