name: CI Develop

on:
  push:
    branches:
      - 'develop'

  pull_request:
    branches:
      - 'develop'
env:
  BASE: ${{ github.ref == 'refs/heads/develop' && 'origin/develop~1' || 'origin/develop' }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - uses: yarn/action-setup@v2.0.1
        with:
          version: 7.1.7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: run lint

      - name: Lint mono
        run: nx affected:lint --base $BASE

      - name: Test mono
        run: nx affected:test --base $BASE

      - name: Build mono
        run: nx affected:build --base $BASE
