name: CI Master

on:
  push:
    branches:
      - 'master'

  pull_request:
    branches:
      - 'master'

env:
  BASE: ${{ github.ref == 'refs/heads/develop' && 'origin/develop~1' || 'origin/develop' }}
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn install

      - name: Lint mono
        run: npx nx affected:lint --base $BASE

      - name: Build mono
        run: npx nx affected:build --base $BASE

      - name: NPM Publish
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          echo '//registry.npmjs.org/:_authToken=${{secrets.NPM_AUTH_TOKEN}}' > .npmrc
          nx affected --target npmSimplePublish --base $BASE
